export const constants = {
  CREATE_CHALLENGE_REQUEST: "CREATE_CHALLENGE_REQUEST",
  CREATE_CHALLENGE_SUCCESS: "CREATE_CHALLENGE_SUCCESS",
  CREATE_CHALLENGE_FAILURE: "CREATE_CHALLENGE_FAILURE",

  CHALLENGES_REQUEST: "CHALLENGES_REQUEST",
  CHALLENGES_SUCCESS: "CHALLENGES_SUCCESS",
  CHALLENGES_FAILURE: "CHALLENGES_FAILURE",
};
